### ISSUE TITLE
Simplify Sign up page

### ISSUE THREAD

**Issue by githagman** [FreeGeekTwinCities/portero#30]
Remove username and password fields

Take users to sign in page or better yet, log them in after saving

**Comment by bdunnette** [comment]
Tom-

I can take a shot at this as a way to get re-acquainted with Portero's innards - unless you're already working on it?

Because of things like this, I'm wondering if the best thing to do (long-term) would be to separate things out a bit: 
- Make a proxy that'll handle requests (like "sign in volunteer x" - maybe something along the lines of [restful-openerp](https://github.com/tgpfeiffer/restful-openerp)?) along with.. 
- A less tightly-coupled front-end (in something like AngularJS?), so that updates to the interface would be easier (e.g. not having to worry about issues between Bootstrap 3 and our Flask templates...)

**Comment by githagman** [comment]
Yeah.. I reinstalled my OS and had to rebuild my python environment, I'm not having luck getting the reqs installed.  In the requirements.txt you have to change it to flask-bootstrap<3 otherwise it grabs bootstrap 3, which is totally incompatible.  Still getting 

```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "portero.py", line 133, in sign_in
    signed_in=signed_in)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tom/freegeek/portero/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/tom/freegeek/portero/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: bootstrap/base.html
```

Here are my versions
Flask (0.10.1)
Flask-Bootstrap (2.3.2.2)
Flask-WTF (0.9.3)

**Comment by githagman** [comment]
So long story short if you have a working environment, don't upgrade...
